# Clase 5: Introducción a Pandas

https://pandas.pydata.org/docs/index.html



---


## Qué es Pandas?

- Biblioteca de Python para manipulación y análisis de datos

- Trabaja con estructuras de datos tipo tablas (DataFrames)

- Ideal para trabajar con datos estructurados (CSV, Excel, SQL, etc)

In [64]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [65]:
# Si es necesario instalar
# !pip install pandas

import pandas as pd
print(f"Versión de Pandas: {pd.__version__}")

Versión de Pandas: 2.2.2

### Conceptos Clave:

- Series: Arreglo unidimensional etiquetado

- DataFrame: Estructura bidimensional tipo tabla

- Índices: Etiquetas para acceder a los datos

## Series vs Dataframe

In [66]:
# Una serie es una columna

edades = pd.Series([20,25,30])

edades

0    20
1    25
2    30
dtype: int64

In [67]:
# Un Dataframe es una tabla

datos = {
    "Nombre":["Ana","Luis","Pedro"],
    "Edad":[20,25,30],
    "Ciudad":["Bogotá","Pereira","Cali"]
}

df = pd.DataFrame(datos)

df

  Nombre  Edad   Ciudad
0    Ana    20   Bogotá
1   Luis    25  Pereira
2  Pedro    30     Cali

## Leer archivos

In [ ]:
# Subir el archivo desde tu computador
from google.colab import files
uploaded = files.upload()

In [ ]:
clientes = pd.read_excel("Clientes.xlsx")

In [ ]:
ventas = pd.read_csv("Ventas (4).csv")

In [ ]:
clientes.head()

In [ ]:
clientes.tail()

## Conociendo el Dataset

In [ ]:
clientes.shape

In [ ]:
clientes.columns

In [ ]:
clientes.info()

In [ ]:
clientes.describe()

In [ ]:
clientes.dtypes

In [ ]:
clientes.sample(5)

## Seleccionar datos

In [ ]:
clientes["ciudad"]

In [ ]:
clientes[["nombre_cliente","ciudad"]]

In [ ]:
# Filas

clientes.iloc[0]

In [ ]:
clientes.iloc[0:5]

## Filtrar información

In [ ]:
# Clientes de Pereira

clientes[clientes["ciudad"] == "Pereira"]

In [ ]:
# Dos condiciones
clientes[
    (clientes["segmento"]== "Premium") &
    (clientes["ciudad"]=="Bogotá")
]

## Crear columnas nuevas

In [ ]:
ventas["IVA"] = df["Precio_Unitario"]*0.19

In [ ]:
ventas["Total"] = ventas["Precio"]+ventas["IVA"]

## Mini reto (15 min)


Preguntas:

* Mostrar las primeras 10 filas.
* Cuántas filas tiene?
* Mostrar solo las columnas:
  * Producto
  * Precio
* Mostrar únicamente productos mayores a $100.000.
* Crear una columna Precio Final.
Mostrar únicamente productos de laptop.