# Actividad 3: Taller EDA
### Entrega: 21 de septiembre

### Instrucciones: 

1. Escoge un conjunto de datos de tu interés ( https://www.kaggle.com/datasets)

2. Utilizando Pandas, realiza:

    •  Exploración de datos nulos, datos duplicados, cantidad de filas y columnas.

    •  Limpieza de datos (Pandas: dropna, fillna, replace, etc.)

    •  Filtrado y selección de datos relevantes para tu análisis

    •  Transformación de columnas, creación de variables nuevas 

    •  Agrupaciones y resúmenes (groupby) 

3. Formula al menos 5 preguntas de análisis sobre tu conjunto de datos.

4. Responde a las pregunta planteadas con una gráfica (con título, nombres en los ejes, leyendas, etc) y una breve interpretación. 

### Conclusiones del análisis

    • Presenta al menos 3 conclusiones relevantes obtenidas a partir del análisis exploratorio. 
    • Las conclusiones deben estar sustentadas en los datos y en los resultados obtenidos. 
    • Menciona patrones, tendencias, relaciones o comportamientos importantes identificados en el conjunto de datos. 
    • Evita limitarte a describir las gráficas; explica qué significan los resultados para el contexto del conjunto de datos.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

In [2]:
# Cargar el archivo
df = pd.read_csv('C:/Users/julya/OneDrive/Cursos2026/BIT_DataScience/DataBases/retail_sales_dataset.csv')
df.shape

(1000, 9)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

In [4]:
df.isnull().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df_strings = df.select_dtypes(include='str')
for col in df_strings.columns:
    print(f"=== Frecuencia de valores en: {col} ===")
    print(df[col].value_counts(dropna=False)) 
    print("\n" + "-"*45 + "\n")

=== Frecuencia de valores en: Date ===
Date
2023-05-16    11
2023-07-14    10
2023-05-23     9
2023-08-05     8
2023-02-05     8
              ..
2023-03-02     1
2023-08-02     1
2023-04-17     1
2023-03-30     1
2023-05-28     1
Name: count, Length: 345, dtype: int64

---------------------------------------------

=== Frecuencia de valores en: Customer ID ===
Customer ID
CUST001     1
CUST002     1
CUST003     1
CUST004     1
CUST005     1
           ..
CUST996     1
CUST997     1
CUST998     1
CUST999     1
CUST1000    1
Name: count, Length: 1000, dtype: int64

---------------------------------------------

=== Frecuencia de valores en: Gender ===
Gender
Female    510
Male      490
Name: count, dtype: int64

---------------------------------------------

=== Frecuencia de valores en: Product Category ===
Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

---------------------------------------------

In [11]:
df['Date'] = pd.to_datetime(df['Date'], format= 'mixed', dayfirst= True, errors= 'coerce')

In [14]:
df['Month'] = df['Date'].dt.month_name()
df['Year'] = df['Date'].dt.year

In [17]:
df

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Month,Year
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,November,2023
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,February,2023
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,January,2023
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,May,2023
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,May,2023
...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,May,2023
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,November,2023
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,October,2023
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,December,2023
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,April,2023

#### Resumen de ventas por categoría de producto

In [36]:
resume_category = df.groupby('Product Category').agg(
    Total_amount = ('Total Amount', 'sum'),
    Sales_mean_by_purchase = ('Total Amount', 'mean'),
    Products_quantity = ('Quantity', 'sum'),
    Price_mean = ('Price per Unit', 'mean')
).reset_index()

resume_category

,Product Category,Total_amount,Sales_mean_by_purchase,Products_quantity,Price_mean
0,Beauty,143515,467.475570,771,184.055375
1,Clothing,155580,443.247863,894,174.287749
2,Electronics,156905,458.786550,849,181.900585

#### Resumen de clientes por genero y edad

In [41]:
resume_gender = df.groupby("Gender").agg(
    Transactions = ('Transaction ID', 'count'),
    Total_amount = ('Total Amount', 'sum'),
    Sales_mean_by_purchase = ('Total Amount', 'mean'),
    age_mean = ('Age', 'mean')
).reset_index()

resume_gender

   Gender  Transactions  Total_amount  Sales_mean_by_purchase   age_mean
0  Female           510        232840              456.549020  41.356863
1    Male           490        223160              455.428571  41.428571

In [ ]:
resume_age = (
    df.groupby("Age", as_index=False)
      .agg(
          Transactions=("Transaction ID", "count"),
          Total_amount=("Total Amount", "sum"),
          Sales_mean_by_purchase=("Total Amount", "mean"),
          gender=("Gender", "nunique")
      )
)

resume_age

TypeError: func is expected but received tuple in **kwargs.

#### Ventas por mes